language: php

php:

- 5.6
- 5.5

before_install:
- sudo apt-get update
- sudo apt-get install make build-essential automake php5-dev php-pear
- git clone git://github.com/jedisct1/libsodium.git
- cd libsodium
- git checkout 1.0.3
- ./autogen.sh
- ./configure && make check
- sudo make install
- sudo pecl install libsodium-beta

install:

- composer install
- composer self-update
- composer update
- chmod +x ./tests/phpunit.sh

script: ./tests/phpunit.sh
